### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by Blockmaestro** [daveshap/GAIA_Initiative#1]
Here's what's going to happen. 

Governments around the world are afraid that citizens will have access to a technology that will eliminate the power differential.There will probably be an "event" that will be orchestrated by state actors. This will be blamed on unregulated AI. The media will endlessly repeat how AI is going to kill all the children and destroy civilization. Social media companies will, undoubtedly, use AI to censor views that oppose the narrative. Since most of the public is technically illiterate, they will believe that the amazing new technology should only be handled, "safely", by altruistic corporations and governments. Low IQ / mentally weak / herd animal type people (for example, the types who use he/her pronouns in their bio.) will gobble this up. 

The media and politicians aren't afraid of disinformation being created. In fact, if you're intellectually honest with yourself, they tell the majority of lies. What they are really terrified of is technology that will automatically find objective truth.

**Comment by daveshap** [comment]
What a tremendous amount of insecurity and projection.
